//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.296
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuickDeploymentModule.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("QuickDeploymentModule.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Getting custom deployment steps....
        /// </summary>
        internal static string CustomDeploymentMessage {
            get {
                return ResourceManager.GetString("CustomDeploymentMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Deploy.
        /// </summary>
        internal static string DeployMenuText {
            get {
                return ResourceManager.GetString("DeployMenuText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deploy to Portal Target....
        /// </summary>
        internal static string DeployTargetPortalText {
            get {
                return ResourceManager.GetString("DeployTargetPortalText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to retrieve deployment items from deployment provider : {0}.
        /// </summary>
        internal static string Error_No_Provider_Items {
            get {
                return ResourceManager.GetString("Error_No_Provider_Items", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gathering deployment files....
        /// </summary>
        internal static string GatheringDeploymentFiles {
            get {
                return ResourceManager.GetString("GatheringDeploymentFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generating Portal Page {0}..
        /// </summary>
        internal static string GeneratingPortalPage {
            get {
                return ResourceManager.GetString("GeneratingPortalPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copying portal files to target.
        /// </summary>
        internal static string Status_Copy_Target_Files {
            get {
                return ResourceManager.GetString("Status_Copy_Target_Files", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Getting Deployment items.
        /// </summary>
        internal static string Status_Deploy_Get_Items {
            get {
                return ResourceManager.GetString("Status_Deploy_Get_Items", resourceCulture);
            }
        }
    }
}
